variable "key-name" {}
variable "instance-name" {}
variable "iam-role" {}
variable "ami" {}
variable "vpc-name" {}
variable "igw-name" {}
variable "public-rt-name" {}
variable "private-rt-name" {}
variable "subnet-name" {}
variable "sg-name" {}
variable "alb_name" {}
variable "listenerName" {}
variable "target_name" {}
variable "public-subnet-name-1" {}
variable "public-subnet-name-2" {}
variable "jumpserver" {}
variable "private-subnet-name-1" {}
variable "private-subnet-name-2" {}